use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    /// Generated by the client the moment the user starts typing.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// "room" | "dm"
    pub context_type: String,
    pub context_id: Uuid,
    pub author_id: Uuid,
    pub content: String,
    /// "streaming" | "complete" | "deleted"
    pub status: String,
    pub started_at: DateTimeUtc,
    pub completed_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
